# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(227, 253)
        MainWindow.setMinimumSize(QtCore.QSize(227, 253))
        MainWindow.setMaximumSize(QtCore.QSize(227, 253))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui/qtfiles/fishing.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(20, 150, 191, 61))
        self.startButton.setObjectName("startButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 191, 31))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.telegramID = QtWidgets.QLineEdit(self.centralwidget)
        self.telegramID.setGeometry(QtCore.QRect(20, 110, 191, 20))
        self.telegramID.setObjectName("telegramID")
        self.windowsCount = QtWidgets.QSpinBox(self.centralwidget)
        self.windowsCount.setGeometry(QtCore.QRect(20, 40, 41, 22))
        self.windowsCount.setObjectName("windowsCount")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_2.setObjectName("label_2")
        self.relaunchButton = QtWidgets.QPushButton(self.centralwidget)
        self.relaunchButton.setGeometry(QtCore.QRect(110, 30, 101, 41))
        self.relaunchButton.setObjectName("relaunchButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 227, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionHow_to_botovodit_GUIDE = QtWidgets.QAction(MainWindow)
        self.actionHow_to_botovodit_GUIDE.setObjectName("actionHow_to_botovodit_GUIDE")
        self.menuHelp.addAction(self.actionHow_to_botovodit_GUIDE)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start observing"))
        self.label.setText(_translate("MainWindow", "Telegram ID?"))
        self.label_2.setText(_translate("MainWindow", "Windows number?"))
        self.relaunchButton.setText(_translate("MainWindow", "Relaunch windows"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHow_to_botovodit_GUIDE.setText(_translate("MainWindow", "How to botovodit`. GUIDE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
